export const STOCK_CHART_REQUEST = 'STOCK_CHART_REQUEST';
export const STOCK_CHART_SUCCESS = 'STOCK_CHART_SUCCESS';
export const STOCK_CHART_FAILURE = 'STOCK_CHART_FAILURE';

export const USER_CHARTS_REQUEST = 'USER_CHARTS_REQUEST';
export const USER_CHARTS_SUCCESS = 'USER_CHARTS_SUCCESS';
export const USER_CHARTS_FAILURE = 'USER_CHARTS_FAILURE';

export const ACTIVE_CHART_REQUEST = 'ACTIVE_CHART_REQUEST';
export const ACTIVE_CHART_SUCCESS = 'ACTIVE_CHART_SUCCESS';
export const ACTIVE_CHART_FAILURE = 'ACTIVE_CHART_FAILURE';

export const GET_ACTIVE_CHART_REQUEST = 'GET_ACTIVE_CHART_REQUEST';
export const GET_ACTIVE_CHART_SUCCESS = 'GET_ACTIVE_CHART_SUCCESS';
export const GET_ACTIVE_CHART_FAILURE = 'GET_ACTIVE_CHART_FAILURE';
