export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_CONFIG_REQUEST = 'USER_CONFIG_REQUEST';
export const USER_CONFIG_SUCCESS = 'USER_CONFIG_SUCCESS';
export const USER_CONFIG_FAILURE = 'USER_CONFIG_FAILURE';

export const ACTIVE_CHART_REQUEST = 'ACTIVE_CHART_REQUEST';
export const ACTIVE_CHART_SUCCESS = 'ACTIVE_CHART_SUCCESS';
export const ACTIVE_CHART_FAILURE = 'ACTIVE_CHART_FAILURE';

export const ADD_CHART_REQUEST = 'ADD_CHART_REQUEST';
export const ADD_CHART_SUCCESS = 'ADD_CHART_SUCCESS';
export const ADD_CHART_FAILURE = 'ADD_CHART_FAILURE';

export const DELETE_CHART_REQUEST = 'DELETE_CHART_REQUEST';
export const DELETE_CHART_SUCCESS = 'DELETE_CHART_SUCCESS';
export const DELETE_CHART_FAILURE = 'DELETE_CHART_FAILURE';
